language: node_js
sudo: false
node_js:
  - stable
  - node
  - 10
  - 11

cache: npm

install: npm ci

git:
  depth: 1

deploy:
  provider: npm
  skip-cleanup: true
  email: "nikeee@outlook.com"
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
    node: stable
